apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "auth_cas.fullname" . }}
  labels:
    app: {{ template "auth_cas.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "auth_cas.fullname" . }}
      run: auth-cas-appserver
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "auth_cas.fullname" . }}
        run: auth-cas-appserver
    spec:
      containers:
      - name: {{ template "auth_cas.fullname" . }}-app
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: CAS_URL
          value: {{ .Values.casURL }}
        - name: INGRESS_HOSTNAME
          value: {{ .Values.authCASHost }}
        - name: NEXTCLOUD_HOST
          value: {{ .Values.nextcloudService }}
        ports:
        - containerPort: 80
